image: atlassian/default-image:3

pipelines:
  pull-requests:
    '**':
      - step:
          name: 'Build and Test'
          script:
            - echo "Zipping Terraform Code."
            - zip -r $BITBUCKET_REPO_SLUG.zip . -x *.git*
          artifacts:
            - '**'
      - step:
          name: 'Upload to S3'
          script:
          - ls
          - pipe: atlassian/aws-s3-deploy:1.1.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: 'eu-west-1'
              S3_BUCKET: '$BUCKET_NAME/aws'
              LOCAL_PATH: '.'
              EXTRA_ARGS: "--exclude=* --include=*.zip"
