variable "ami_id" {
  description = "AMI ID for the EC2 instance"
  type        = string
  default     = "ami-0453ec754f44f9a4a"  # Default Amazon Linux AMI free tear
}

variable "instance_type" {
  description = "EC2 instance type"
  type        = string
  default     = "t2.micro"
}

variable "vpc_id" {
  description = "VPC ID where EC2 will be deployed"
  type        = string
}

variable "private_subnet_id" {
  description = "Private subnet ID for EC2 instance"
  type        = string
}

# Tags ------------------------------------

variable "devops_name" {
  description = "DevOps Name"
  type        = string
  default     = "Shimon"
}

variable "generated_by" {
  description = "Generated By"
  type        = string
  default     = "Terraform"
}

variable "scope" {
  description = "Scope of the resources"
  type        = string
  default     = "for deploying OpenVPN"
}

variable "owner" {
  description = "Owner of the resources"
  type        = string
  default     = "Shimon Mizrahi"
}

variable "environment" {
  description = "Environment tag (e.g., dev, staging, prod)"
  type        = string
}
